version: '3'
services:
  app:
    build:
      context: .
      args:
        - enable_mecab=1
    platform: linux/amd64
    volumes:
      - './font.ttf:/ai/font.ttf:ro'
      - '/data:/ai/data'
    restart: always
